name: Build

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: ${{ matrix.target.platform }} / Scala ${{ matrix.target.scala }}
    strategy:
      matrix:
        target:
          - { project: root2_12, scala: "2.12", platform: jvm }
          - { project: root2_13, scala: "2.13", platform: jvm }
          - { project: root, scala: "3.8", platform: jvm }
          - { project: rootJS2_12, scala: "2.12", platform: js }
          - { project: rootJS2_13, scala: "2.13", platform: js }
          - { project: rootJS, scala: "3.8", platform: js }
          - { project: rootNative2_12, scala: "2.12", platform: native }
          - { project: rootNative2_13, scala: "2.13", platform: native }
          - { project: rootNative, scala: "3.8", platform: native }
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Java (temurin@25)
        id: setup-java-temurin-25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: sbt update
        if: steps.setup-java-temurin-25.outputs.cache-hit == 'false'
        run: sbt '${{ matrix.target.project }}/update'

      - name: Check headers and formatting
        run: sbt '${{ matrix.target.project }}/headerCheckAll; ${{ matrix.target.project }}/scalafmtCheckAll; scalafmtSbtCheck'

      - name: scalaJSLink
        if: matrix.target.platform == 'js'
        run: sbt '${{ matrix.target.project }}/Test/scalaJSLinkerResult'

      - name: nativeLink
        if: matrix.target.platform == 'native'
        run: sbt '${{ matrix.target.project }}/Test/nativeLink'

      - name: Test
        run: sbt '${{ matrix.target.project }}/testFull'

  publish:
    name: Publish Artifacts
    needs: [ build ]
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Java (temurin@25)
        id: setup-java-temurin-25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: sbt update
        if: steps.setup-java-temurin-25.outputs.cache-hit == 'false'
        run: sbt update

      - name: Publish
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
